/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HealthcareProviderService } from "../healthcareProvider.service";
import { HealthcareProviderCreateInput } from "./HealthcareProviderCreateInput";
import { HealthcareProvider } from "./HealthcareProvider";
import { HealthcareProviderFindManyArgs } from "./HealthcareProviderFindManyArgs";
import { HealthcareProviderWhereUniqueInput } from "./HealthcareProviderWhereUniqueInput";
import { HealthcareProviderUpdateInput } from "./HealthcareProviderUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class HealthcareProviderControllerBase {
  constructor(protected readonly service: HealthcareProviderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HealthcareProvider })
  async createHealthcareProvider(
    @common.Body() data: HealthcareProviderCreateInput
  ): Promise<HealthcareProvider> {
    return await this.service.createHealthcareProvider({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
        role: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [HealthcareProvider] })
  @ApiNestedQuery(HealthcareProviderFindManyArgs)
  async healthcareProviders(
    @common.Req() request: Request
  ): Promise<HealthcareProvider[]> {
    const args = plainToClass(HealthcareProviderFindManyArgs, request.query);
    return this.service.healthcareProviders({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
        role: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HealthcareProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async healthcareProvider(
    @common.Param() params: HealthcareProviderWhereUniqueInput
  ): Promise<HealthcareProvider | null> {
    const result = await this.service.healthcareProvider({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
        role: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HealthcareProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateHealthcareProvider(
    @common.Param() params: HealthcareProviderWhereUniqueInput,
    @common.Body() data: HealthcareProviderUpdateInput
  ): Promise<HealthcareProvider | null> {
    try {
      return await this.service.updateHealthcareProvider({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          password: true,
          role: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HealthcareProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteHealthcareProvider(
    @common.Param() params: HealthcareProviderWhereUniqueInput
  ): Promise<HealthcareProvider | null> {
    try {
      return await this.service.deleteHealthcareProvider({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          password: true,
          role: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: HealthcareProviderWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        startDate: true,
        endDate: true,
        preferredShift: true,
        photoDialysisCard: true,
        telephoneContacts: true,
        medicalPrescription: true,

        patient: {
          select: {
            id: true,
          },
        },

        healthcareProvider: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: HealthcareProviderWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateHealthcareProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: HealthcareProviderWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateHealthcareProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: HealthcareProviderWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateHealthcareProvider({
      where: params,
      data,
      select: { id: true },
    });
  }
}
