/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DialysisCenterService } from "../dialysisCenter.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DialysisCenterCreateInput } from "./DialysisCenterCreateInput";
import { DialysisCenter } from "./DialysisCenter";
import { DialysisCenterFindManyArgs } from "./DialysisCenterFindManyArgs";
import { DialysisCenterWhereUniqueInput } from "./DialysisCenterWhereUniqueInput";
import { DialysisCenterUpdateInput } from "./DialysisCenterUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DialysisCenterControllerBase {
  constructor(
    protected readonly service: DialysisCenterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DialysisCenter })
  @nestAccessControl.UseRoles({
    resource: "DialysisCenter",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDialysisCenter(
    @common.Body() data: DialysisCenterCreateInput
  ): Promise<DialysisCenter> {
    return await this.service.createDialysisCenter({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        seatCount: true,
        shiftMorning: true,
        shiftAfternoon: true,
        shiftEvening: true,
        availableAfternoonPlaces: true,
        availableEveningPlaces: true,
        availableMorningPlaces: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DialysisCenter] })
  @ApiNestedQuery(DialysisCenterFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DialysisCenter",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dialysisCenters(
    @common.Req() request: Request
  ): Promise<DialysisCenter[]> {
    const args = plainToClass(DialysisCenterFindManyArgs, request.query);
    return this.service.dialysisCenters({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        seatCount: true,
        shiftMorning: true,
        shiftAfternoon: true,
        shiftEvening: true,
        availableAfternoonPlaces: true,
        availableEveningPlaces: true,
        availableMorningPlaces: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DialysisCenter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DialysisCenter",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dialysisCenter(
    @common.Param() params: DialysisCenterWhereUniqueInput
  ): Promise<DialysisCenter | null> {
    const result = await this.service.dialysisCenter({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        seatCount: true,
        shiftMorning: true,
        shiftAfternoon: true,
        shiftEvening: true,
        availableAfternoonPlaces: true,
        availableEveningPlaces: true,
        availableMorningPlaces: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DialysisCenter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DialysisCenter",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDialysisCenter(
    @common.Param() params: DialysisCenterWhereUniqueInput,
    @common.Body() data: DialysisCenterUpdateInput
  ): Promise<DialysisCenter | null> {
    try {
      return await this.service.updateDialysisCenter({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          seatCount: true,
          shiftMorning: true,
          shiftAfternoon: true,
          shiftEvening: true,
          availableAfternoonPlaces: true,
          availableEveningPlaces: true,
          availableMorningPlaces: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DialysisCenter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DialysisCenter",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDialysisCenter(
    @common.Param() params: DialysisCenterWhereUniqueInput
  ): Promise<DialysisCenter | null> {
    try {
      return await this.service.deleteDialysisCenter({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          seatCount: true,
          shiftMorning: true,
          shiftAfternoon: true,
          shiftEvening: true,
          availableAfternoonPlaces: true,
          availableEveningPlaces: true,
          availableMorningPlaces: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
